### ISSUE TITLE
Request password to encrypt, decrypt and sign messages

### ISSUE THREAD

**Issue by iamcais** [MarinX/yap#11]

**Comment by MarinX** [comment]
Hi @iamcais ,

I can understand the feature you want, but, do you have any thoughts on where do you want to show this option?
Currently, YAP is around contacts / keys.

**Comment by iamcais** [comment]
In the last update you activated the PIN option is enough, congratulations on the excellent application ... hello from Brazil.

**Comment by MarinX** [comment]
thank you! ok, closing the issue
