### ISSUE TITLE
Fingerprints won't work

### ISSUE THREAD

**Issue by KevinZonda** [MarinX/yap#12]
**Describe the bug**
Fingerprints won't work

**To Reproduce**
Set a pin, and when unlocking, click the fp's button, no response given.

**Expected behavior**
FP can be used to verify.

**Screenshots**
![Screenshot_20210217-005152](https://user-images.githubusercontent.com/33132228/108140996-d1bd3c80-70ba-11eb-8762-273d63be634d.jpg)

**Smartphone (please complete the following information):**
 - Device: SAMSUNG S20
 - OS: Android
 - Version: R

**Additional context**
undefined

**Comment by MarinX** [comment]
Hi @KevinZonda ,

Thank you for the report.
It's fixed and pushed on gplay.
The update should arrive today.

**Comment by KevinZonda** [comment]
Thank you!
